export const environment = {
  production: false,
  apiUrl: 'https://sytedev01.mobileye.com/',
  sourceId: 'b09a7990-05ea-4af9-81ef-edfab16c4e31',
  searchByEmployeeIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/search.png?csf=1&e=Pw6FCx',
  searchByDepartmentIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/departments.png?csf=1&e=E0yEvS',
  searchByLocationIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/tag-search.png?csf=1&e=tByaHK',
  menuIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/more_vert-black-18dp%20(3).svg?csf=1&e=ZgPfPm',
  departmentIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/department.png',
  workPhoneIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/phone.png',
  workPhoneHoverIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/work_phone_hover_fixed.png',
  mobilePhoneIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/mobile.png',
  mobilePhoneHoverIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/mobile-hover.png',
  azIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/sorting%20a-z%20copy.png',
  zaIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/sorting%20z-a%20copy.png',
  emailIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/mail_default.png',
  emailHover: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/mail.png',
  jobIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/Job.png',
  locationIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/location.png',
  locationHoverIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/location-hover.png',
  managerIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/manager.png',
  managerHoverIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/manager-hover.png',
  workaDayIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/workday.png',
  workaDayHoverIcon: 'https://sytedev01.mobileye.com/SiteAssets/icons/search-page%20icons/icons_transparent/workday-hover.png'
};
